### ISSUE TITLE
授权后分享失败问题

### ISSUE THREAD

**Issue by yi821661664** [bytedance/DouyinOpenPlatformDemo#5]
https://www.yuque.com/qiseliuli/fxwhgd/vpohs7avam25rfnr?singleDoc# 《抖音授权后分享失败的问题排查》

**Comment by yi821661664** [comment]
场景：由于业务需要，我先调用了授权，拿到授权信息，然后再调用分享

**Comment by yi821661664** [comment]
场景：由于业务需要，我先调用了授权，拿到授权信息，然后再调用分享，某些设备出现了两次授权的情况，并且没有拉起分享页面。单独分享或者授权都是没问题的，但是合在一起就不行，希望大佬能帮忙看看原因，谢谢

**Comment by yi821661664** [comment]
先授权，再在回调重分享，会两次拉起授权，反过来，先分享，再在回调中授权，会两次拉起分享，希望大佬看看原因

**Comment by Aevit** [comment]
可以去抖音开放平台官网 (https://developer.open-douyin.com/) 在线客服那里提问题，那里会有人值班处理的
