### ISSUE TITLE
iOS Demo 无法正常下载

### ISSUE THREAD

**Issue by ShangchengShi** [bytedance/DouyinOpenPlatformDemo#6]
按照 ReadMe:https://github.com/bytedance/DouyinOpenPlatformDemo/blob/master/iOS/README.md 执行 git lfs pull 之后，出现报错信息：

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
Failed to fetch some objects from 'https://github.com/bytedance/DouyinOpenPlatformDemo.git/info/lfs'

**Comment by Aevit** [comment]
fixed. just try `git pull` and `pod install`
